# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.xg_boost_series_optimization_config import XGBoostSeriesOptimizationConfig  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestXGBoostSeriesOptimizationConfig(unittest.TestCase):
    """XGBoostSeriesOptimizationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test XGBoostSeriesOptimizationConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.xg_boost_series_optimization_config.XGBoostSeriesOptimizationConfig()  # noqa: E501
        if include_optional :
            return XGBoostSeriesOptimizationConfig(
                input_window_range_configs = [
                    blackfox_restapi.models.input_window_range_config.InputWindowRangeConfig(
                        window = null, 
                        shift = null, 
                        step = null, 
                        aggregation_types = ["None","Avg","Sum"], )
                    ], 
                output_window_configs = [
                    blackfox_restapi.models.output_window_config.OutputWindowConfig(
                        window = 56, 
                        shift = 56, )
                    ], 
                output_sample_step = 56, 
                dataset_id = '0', 
                inputs = [
                    blackfox_restapi.models.input_config.InputConfig(
                        range = null, 
                        is_optional = True, )
                    ], 
                output_ranges = [
                    blackfox_restapi.models.range.Range(
                        min = 1.337, 
                        max = 1.337, )
                    ], 
                validation_split = 1.337, 
                random_seed = 56, 
                problem_type = Regression, 
                binary_optimization_metric = Auc, 
                max_depth = null, 
                min_child_weight = null, 
                gamma = null, 
                subsample = null, 
                colsample_bytree = null, 
                reg_alpha = null, 
                learning_rate = null, 
                engine_config = null
            )
        else :
            return XGBoostSeriesOptimizationConfig(
                max_depth = null,
                min_child_weight = null,
                gamma = null,
                subsample = null,
                colsample_bytree = null,
                reg_alpha = null,
                learning_rate = null,
        )

    def testXGBoostSeriesOptimizationConfig(self):
        """Test XGBoostSeriesOptimizationConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
