# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox_restapi
from blackfox_restapi.api.network_api import NetworkApi  # noqa: E501
from blackfox_restapi.rest import ApiException


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = blackfox_restapi.api.network_api.NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get(self):
        """Test case for get

        Download nework file (*.h5)  # noqa: E501
        """
        pass

    def test_get_metadata(self):
        """Test case for get_metadata

        Get h5 file metadata  # noqa: E501
        """
        pass

    def test_head(self):
        """Test case for head

        Check if h5 file exist  # noqa: E501
        """
        pass

    def test_post(self):
        """Test case for post

        Upload h5 file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
