# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.rnn_optimization_config import RnnOptimizationConfig  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestRnnOptimizationConfig(unittest.TestCase):
    """RnnOptimizationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RnnOptimizationConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.rnn_optimization_config.RnnOptimizationConfig()  # noqa: E501
        if include_optional :
            return RnnOptimizationConfig(
                dropout = null, 
                batch_size = 56, 
                recurrent_dropout = null, 
                recurrent_output_count = 56, 
                dataset_id = '0', 
                inputs = [
                    blackfox_restapi.models.input_config.InputConfig(
                        range = null, 
                        is_optional = True, )
                    ], 
                output_ranges = [
                    blackfox_restapi.models.range.Range(
                        min = 1.337, 
                        max = 1.337, )
                    ], 
                hidden_layer_count_range = null, 
                neurons_per_layer = null, 
                training_algorithms = [
                    'SGD'
                    ], 
                activation_functions = [
                    'SoftMax'
                    ], 
                recurrent_activation_functions = [
                    'SoftMax'
                    ], 
                max_epoch = 1, 
                validation_split = 0, 
                random_seed = 56, 
                recurrent_input_count_range = null, 
                engine_config = null
            )
        else :
            return RnnOptimizationConfig(
                max_epoch = 1,
                validation_split = 0,
        )

    def testRnnOptimizationConfig(self):
        """Test RnnOptimizationConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
