# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox_restapi
from blackfox_restapi.models.keras_recurrent_hidden_layer_config import KerasRecurrentHiddenLayerConfig  # noqa: E501
from blackfox_restapi.rest import ApiException


class TestKerasRecurrentHiddenLayerConfig(unittest.TestCase):
    """KerasRecurrentHiddenLayerConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKerasRecurrentHiddenLayerConfig(self):
        """Test KerasRecurrentHiddenLayerConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blackfox_restapi.models.keras_recurrent_hidden_layer_config.KerasRecurrentHiddenLayerConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
