# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox_restapi
from blackfox_restapi.models.keras_recurrent_optimization_config import KerasRecurrentOptimizationConfig  # noqa: E501
from blackfox_restapi.rest import ApiException


class TestKerasRecurrentOptimizationConfig(unittest.TestCase):
    """KerasRecurrentOptimizationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKerasRecurrentOptimizationConfig(self):
        """Test KerasRecurrentOptimizationConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blackfox_restapi.models.keras_recurrent_optimization_config.KerasRecurrentOptimizationConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
