# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.ann_model import AnnModel  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestAnnModel(unittest.TestCase):
    """AnnModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AnnModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.ann_model.AnnModel()  # noqa: E501
        if include_optional :
            return AnnModel(
                hidden_layers = [
                    blackfox_restapi.models.ann_hidden_layer_config.AnnHiddenLayerConfig(
                        neuron_count = 56, 
                        activation_function = None, 
                        dropout = 1.337, )
                    ], 
                training_algorithm = None, 
                output_layer_activation_function = None, 
                feature_selection = [
                    True
                    ]
            )
        else :
            return AnnModel(
        )

    def testAnnModel(self):
        """Test AnnModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
