# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox_restapi
from blackfox_restapi.api.optimization_api import OptimizationApi  # noqa: E501
from blackfox_restapi.rest import ApiException


class TestOptimizationApi(unittest.TestCase):
    """OptimizationApi unit test stubs"""

    def setUp(self):
        self.api = blackfox_restapi.api.optimization_api.OptimizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_status(self):
        """Test case for get_status

        Get status of optimization  # noqa: E501
        """
        pass

    def test_post(self):
        """Test case for post

        Starts new optimization using keras  # noqa: E501
        """
        pass

    def test_post_action(self):
        """Test case for post_action

        Stop or cancel running optimization  # noqa: E501
        """
        pass

    def test_post_forest(self):
        """Test case for post_forest

        Starts new series optimization using keras  # noqa: E501
        """
        pass

    def test_post_series(self):
        """Test case for post_series

        Starts new series optimization using keras  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
