# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.ann_training_config import AnnTrainingConfig  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestAnnTrainingConfig(unittest.TestCase):
    """AnnTrainingConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AnnTrainingConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.ann_training_config.AnnTrainingConfig()  # noqa: E501
        if include_optional :
            return AnnTrainingConfig(
                batch_size = 56, 
                dataset_id = '0', 
                input_ranges = [
                    blackfox_restapi.models.range.Range(
                        min = 1.337, 
                        max = 1.337, )
                    ], 
                output_layer = None, 
                hidden_layer_configs = [
                    blackfox_restapi.models.ann_hidden_layer_config.AnnHiddenLayerConfig(
                        neuron_count = 56, 
                        activation_function = None, 
                        dropout = 1.337, )
                    ], 
                training_algorithm = None, 
                max_epoch = 1, 
                cross_validation = True, 
                validation_split = 0, 
                random_seed = 56
            )
        else :
            return AnnTrainingConfig(
                max_epoch = 1,
                validation_split = 0,
        )

    def testAnnTrainingConfig(self):
        """Test AnnTrainingConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
