# coding: utf-8

"""
    BlackFox

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blackfox_restapi
from blackfox_restapi.models.keras_series_training_config import KerasSeriesTrainingConfig  # noqa: E501
from blackfox_restapi.rest import ApiException


class TestKerasSeriesTrainingConfig(unittest.TestCase):
    """KerasSeriesTrainingConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKerasSeriesTrainingConfig(self):
        """Test KerasSeriesTrainingConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blackfox_restapi.models.keras_series_training_config.KerasSeriesTrainingConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
