# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.ann_optimized_model import AnnOptimizedModel  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestAnnOptimizedModel(unittest.TestCase):
    """AnnOptimizedModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AnnOptimizedModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.ann_optimized_model.AnnOptimizedModel()  # noqa: E501
        if include_optional :
            return AnnOptimizedModel(
                id = '0', 
                hidden_layers = [
                    blackfox_restapi.models.ann_hidden_layer_config.AnnHiddenLayerConfig(
                        neuron_count = 56, 
                        activation_function = null, 
                        dropout = 1.337, )
                    ], 
                training_algorithm = null, 
                output_layer_activation_function = null, 
                feature_selection = [
                    True
                    ]
            )
        else :
            return AnnOptimizedModel(
        )

    def testAnnOptimizedModel(self):
        """Test AnnOptimizedModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
