# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.ann_series_optimization_config import AnnSeriesOptimizationConfig  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestAnnSeriesOptimizationConfig(unittest.TestCase):
    """AnnSeriesOptimizationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AnnSeriesOptimizationConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.ann_series_optimization_config.AnnSeriesOptimizationConfig()  # noqa: E501
        if include_optional :
            return AnnSeriesOptimizationConfig(
                input_window_range_configs = [
                    blackfox_restapi.models.input_window_range_config.InputWindowRangeConfig(
                        window = None, 
                        shift = None, 
                        step = None, 
                        aggregation_types = ["None","Avg","Sum"], )
                    ], 
                output_window_configs = [
                    blackfox_restapi.models.output_window_config.OutputWindowConfig(
                        window = 56, 
                        shift = 56, )
                    ], 
                output_sample_step = 56, 
                dropout = None, 
                batch_size = 56, 
                dataset_id = '0', 
                inputs = [
                    blackfox_restapi.models.input_config.InputConfig(
                        range = None, 
                        is_optional = True, )
                    ], 
                output_ranges = [
                    blackfox_restapi.models.range.Range(
                        min = 1.337, 
                        max = 1.337, )
                    ], 
                problem_type = Regression, 
                binary_optimization_metric = ROCAUC, 
                hidden_layer_count_range = {"min":1,"max":15}, 
                neurons_per_layer = {"min":1,"max":10}, 
                training_algorithms = ["Adadelta","Adagrad","Adam","Adamax","Nadam","RMSprop","SGD"], 
                activation_functions = ["Elu","HardSigmoid","Linear","ReLu","Selu","Sigmoid","SoftMax","SoftPlus","SoftSign","TanH"], 
                max_epoch = 1, 
                cross_validation = True, 
                validation_split = 0, 
                random_seed = 56, 
                engine_config = None
            )
        else :
            return AnnSeriesOptimizationConfig(
                max_epoch = 1,
                validation_split = 0,
        )

    def testAnnSeriesOptimizationConfig(self):
        """Test AnnSeriesOptimizationConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
