# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import blackfox_restapi
from blackfox_restapi.api.data_set_api import DataSetApi  # noqa: E501
from blackfox_restapi.rest import ApiException


class TestDataSetApi(unittest.TestCase):
    """DataSetApi unit test stubs"""

    def setUp(self):
        self.api = blackfox_restapi.api.data_set_api.DataSetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download(self):
        """Test case for download

        Download dataset file (*.csv)  # noqa: E501
        """
        pass

    def test_exists(self):
        """Test case for exists

        Check if dataset file exist  # noqa: E501
        """
        pass

    def test_upload(self):
        """Test case for upload

        Upload dataset file (*.csv)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
