# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import blackfox_restapi
from blackfox_restapi.api.info_api import InfoApi  # noqa: E501
from blackfox_restapi.rest import ApiException


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = blackfox_restapi.api.info_api.InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_version(self):
        """Test case for version

        """
        pass


if __name__ == '__main__':
    unittest.main()
