# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.trained_network import TrainedNetwork  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestTrainedNetwork(unittest.TestCase):
    """TrainedNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TrainedNetwork
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.trained_network.TrainedNetwork()  # noqa: E501
        if include_optional :
            return TrainedNetwork(
                id = '0', 
                epoch_count = 56, 
                errors_on_validation_set = [
                    1.337
                    ], 
                errors_on_training_set = [
                    1.337
                    ]
            )
        else :
            return TrainedNetwork(
        )

    def testTrainedNetwork(self):
        """Test TrainedNetwork"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
