# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import blackfox_restapi
from blackfox_restapi.models.random_forest_model import RandomForestModel  # noqa: E501
from blackfox_restapi.rest import ApiException

class TestRandomForestModel(unittest.TestCase):
    """RandomForestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RandomForestModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = blackfox_restapi.models.random_forest_model.RandomForestModel()  # noqa: E501
        if include_optional :
            return RandomForestModel(
                number_of_estimators = 56, 
                max_depth = 56, 
                max_features = 56, 
                feature_selection = [
                    True
                    ]
            )
        else :
            return RandomForestModel(
        )

    def testRandomForestModel(self):
        """Test RandomForestModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
