# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from blackfox_restapi.configuration import Configuration


class AnnLayerConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'activation_function': 'NeuralNetworkActivationFunction',
        'ranges': 'list[Range]'
    }

    attribute_map = {
        'activation_function': 'activationFunction',
        'ranges': 'ranges'
    }

    def __init__(self, activation_function=None, ranges=None, local_vars_configuration=None):  # noqa: E501
        """AnnLayerConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._activation_function = None
        self._ranges = None
        self.discriminator = None

        if activation_function is not None:
            self.activation_function = activation_function
        self.ranges = ranges

    @property
    def activation_function(self):
        """Gets the activation_function of this AnnLayerConfig.  # noqa: E501

        Layer activation function  # noqa: E501

        :return: The activation_function of this AnnLayerConfig.  # noqa: E501
        :rtype: NeuralNetworkActivationFunction
        """
        return self._activation_function

    @activation_function.setter
    def activation_function(self, activation_function):
        """Sets the activation_function of this AnnLayerConfig.

        Layer activation function  # noqa: E501

        :param activation_function: The activation_function of this AnnLayerConfig.  # noqa: E501
        :type: NeuralNetworkActivationFunction
        """

        self._activation_function = activation_function

    @property
    def ranges(self):
        """Gets the ranges of this AnnLayerConfig.  # noqa: E501


        :return: The ranges of this AnnLayerConfig.  # noqa: E501
        :rtype: list[Range]
        """
        return self._ranges

    @ranges.setter
    def ranges(self, ranges):
        """Sets the ranges of this AnnLayerConfig.


        :param ranges: The ranges of this AnnLayerConfig.  # noqa: E501
        :type: list[Range]
        """

        self._ranges = ranges

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnnLayerConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AnnLayerConfig):
            return True

        return self.to_dict() != other.to_dict()
