# coding: utf-8

"""
    BlackFox

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from blackfox_restapi.configuration import Configuration


class RnnOptimizationStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'epoch': 'int',
        'state': 'OptimizationState',
        'generation': 'int',
        'total_generations': 'int',
        'validation_set_error': 'float',
        'training_set_error': 'float',
        'model': 'RnnOptimizedModel'
    }

    attribute_map = {
        'epoch': 'epoch',
        'state': 'state',
        'generation': 'generation',
        'total_generations': 'totalGenerations',
        'validation_set_error': 'validationSetError',
        'training_set_error': 'trainingSetError',
        'model': 'model'
    }

    def __init__(self, epoch=None, state=None, generation=None, total_generations=None, validation_set_error=None, training_set_error=None, model=None, local_vars_configuration=None):  # noqa: E501
        """RnnOptimizationStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._epoch = None
        self._state = None
        self._generation = None
        self._total_generations = None
        self._validation_set_error = None
        self._training_set_error = None
        self._model = None
        self.discriminator = None

        if epoch is not None:
            self.epoch = epoch
        if state is not None:
            self.state = state
        if generation is not None:
            self.generation = generation
        if total_generations is not None:
            self.total_generations = total_generations
        if validation_set_error is not None:
            self.validation_set_error = validation_set_error
        if training_set_error is not None:
            self.training_set_error = training_set_error
        self.model = model

    @property
    def epoch(self):
        """Gets the epoch of this RnnOptimizationStatus.  # noqa: E501

        Number of epoch for current best model  # noqa: E501

        :return: The epoch of this RnnOptimizationStatus.  # noqa: E501
        :rtype: int
        """
        return self._epoch

    @epoch.setter
    def epoch(self, epoch):
        """Sets the epoch of this RnnOptimizationStatus.

        Number of epoch for current best model  # noqa: E501

        :param epoch: The epoch of this RnnOptimizationStatus.  # noqa: E501
        :type: int
        """

        self._epoch = epoch

    @property
    def state(self):
        """Gets the state of this RnnOptimizationStatus.  # noqa: E501

        Optimization state (Active, Finished, Stopped, Error)  # noqa: E501

        :return: The state of this RnnOptimizationStatus.  # noqa: E501
        :rtype: OptimizationState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this RnnOptimizationStatus.

        Optimization state (Active, Finished, Stopped, Error)  # noqa: E501

        :param state: The state of this RnnOptimizationStatus.  # noqa: E501
        :type: OptimizationState
        """

        self._state = state

    @property
    def generation(self):
        """Gets the generation of this RnnOptimizationStatus.  # noqa: E501

        Current generation  # noqa: E501

        :return: The generation of this RnnOptimizationStatus.  # noqa: E501
        :rtype: int
        """
        return self._generation

    @generation.setter
    def generation(self, generation):
        """Sets the generation of this RnnOptimizationStatus.

        Current generation  # noqa: E501

        :param generation: The generation of this RnnOptimizationStatus.  # noqa: E501
        :type: int
        """

        self._generation = generation

    @property
    def total_generations(self):
        """Gets the total_generations of this RnnOptimizationStatus.  # noqa: E501

        Total number of generations  # noqa: E501

        :return: The total_generations of this RnnOptimizationStatus.  # noqa: E501
        :rtype: int
        """
        return self._total_generations

    @total_generations.setter
    def total_generations(self, total_generations):
        """Sets the total_generations of this RnnOptimizationStatus.

        Total number of generations  # noqa: E501

        :param total_generations: The total_generations of this RnnOptimizationStatus.  # noqa: E501
        :type: int
        """

        self._total_generations = total_generations

    @property
    def validation_set_error(self):
        """Gets the validation_set_error of this RnnOptimizationStatus.  # noqa: E501

        Error on validation set  # noqa: E501

        :return: The validation_set_error of this RnnOptimizationStatus.  # noqa: E501
        :rtype: float
        """
        return self._validation_set_error

    @validation_set_error.setter
    def validation_set_error(self, validation_set_error):
        """Sets the validation_set_error of this RnnOptimizationStatus.

        Error on validation set  # noqa: E501

        :param validation_set_error: The validation_set_error of this RnnOptimizationStatus.  # noqa: E501
        :type: float
        """

        self._validation_set_error = validation_set_error

    @property
    def training_set_error(self):
        """Gets the training_set_error of this RnnOptimizationStatus.  # noqa: E501

        Error on training set  # noqa: E501

        :return: The training_set_error of this RnnOptimizationStatus.  # noqa: E501
        :rtype: float
        """
        return self._training_set_error

    @training_set_error.setter
    def training_set_error(self, training_set_error):
        """Sets the training_set_error of this RnnOptimizationStatus.

        Error on training set  # noqa: E501

        :param training_set_error: The training_set_error of this RnnOptimizationStatus.  # noqa: E501
        :type: float
        """

        self._training_set_error = training_set_error

    @property
    def model(self):
        """Gets the model of this RnnOptimizationStatus.  # noqa: E501

        Best model, only set if optimization is finished  # noqa: E501

        :return: The model of this RnnOptimizationStatus.  # noqa: E501
        :rtype: RnnOptimizedModel
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this RnnOptimizationStatus.

        Best model, only set if optimization is finished  # noqa: E501

        :param model: The model of this RnnOptimizationStatus.  # noqa: E501
        :type: RnnOptimizedModel
        """

        self._model = model

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RnnOptimizationStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RnnOptimizationStatus):
            return True

        return self.to_dict() != other.to_dict()
